//
// Created by shilopadael on 5/17/23.
//

#ifndef ROBOT_NAVIGATION_WORKSHOP_GLOBALSDEFINES_H
#define ROBOT_NAVIGATION_WORKSHOP_GLOBALSDEFINES_H

#define HALLWAY 0
#define WALL 1
#define DOOR 2
#define EXIT_POINT 3
#define ENTRY_POINT 4
//#define UNKNOWN 5


#endif //ROBOT_NAVIGATION_WORKSHOP_GLOBALSDEFINES_H
