//
// Created by omer on 5/7/23.
//

#ifndef ROBOT_NAVIGATION_WORKSHOP_EXITROOMBEHAIVOR_H
#define ROBOT_NAVIGATION_WORKSHOP_EXITROOMBEHAIVOR_H


class ExitRoomBehaivor {

};


#endif //ROBOT_NAVIGATION_WORKSHOP_EXITROOMBEHAIVOR_H
