//
// Created by omer on 5/7/23.
//

#ifndef ROBOT_NAVIGATION_WORKSHOP_HALLNAVIGATIONBEHAIVOR_H
#define ROBOT_NAVIGATION_WORKSHOP_HALLNAVIGATIONBEHAIVOR_H


class HallNavigationBehaivor {

};


#endif //ROBOT_NAVIGATION_WORKSHOP_HALLNAVIGATIONBEHAIVOR_H
