//
// Created by omer on 5/5/23.
//

#ifndef ROBOT_NAVIGATION_WORKSHOP_NAVIGATETOCENTERROOMCOMMAND_H
#define ROBOT_NAVIGATION_WORKSHOP_NAVIGATETOCENTERROOMCOMMAND_H


class navigateToCenterRoomCommand {

};


#endif //ROBOT_NAVIGATION_WORKSHOP_NAVIGATETOCENTERROOMCOMMAND_H
