//
// Created by omer on 5/5/23.
//

#ifndef ROBOT_NAVIGATION_WORKSHOP_NAVIGATETOEXITCOMMAND_H
#define ROBOT_NAVIGATION_WORKSHOP_NAVIGATETOEXITCOMMAND_H


class navigateToExitCommand {

};


#endif //ROBOT_NAVIGATION_WORKSHOP_NAVIGATETOEXITCOMMAND_H
