//
// Created by omer on 5/8/23.
//

#ifndef ROBOT_NAVIGATION_WORKSHOP_EXITROOMBEHAVIOR_H
#define ROBOT_NAVIGATION_WORKSHOP_EXITROOMBEHAVIOR_H


class ExitRoomBehavior {

};


#endif //ROBOT_NAVIGATION_WORKSHOP_EXITROOMBEHAVIOR_H
