//
// Created by omer on 5/5/23.
//

#ifndef ROBOT_NAVIGATION_WORKSHOP_ROBOTMISSIONFACTORY_H
#define ROBOT_NAVIGATION_WORKSHOP_ROBOTMISSIONFACTORY_H


class RobotMissionFactory {

};


#endif //ROBOT_NAVIGATION_WORKSHOP_ROBOTMISSIONFACTORY_H
