//
// Created by ofirhelerman on 6/11/23.
//

#ifndef ROBOT_NAVIGATION_WORKSHOP_ROOMTOROOMNAVIGATION_H
#define ROBOT_NAVIGATION_WORKSHOP_ROOMTOROOMNAVIGATION_H


class RoomToRoomNavigation {

};


#endif //ROBOT_NAVIGATION_WORKSHOP_ROOMTOROOMNAVIGATION_H
